name: Deploy docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Deploy docs
        run: |
          python -m pip install uv
          python -m uv sync --only-group docs
          mkdocs gh-deploy --force --clean --verbose
