name: Python Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gdal-bin libgdal-dev
          python -m pip install uv
          python -m uv sync

      - name: Run tests
        run: |
          pytest
