name: Python Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/tests.yml'

jobs:
  tests:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install uv
          python -m uv sync --all-groups

      - name: Run tests
        run: |
          uv run pytest
